export enum GameControls {
  // Movement
  MOVE_UP = "MOVE_UP",
  MOVE_DOWN = "MOVE_DOWN",
  MOVE_LEFT = "MOVE_LEFT",
  MOVE_RIGHT = "MOVE_RIGHT",

  // Primary actions
  ACTION_SHOOT = "ACTION_SHOOT",
  ACTION_RELOAD = "ACTION_RELOAD",
  ACTION_INTERACT = "ACTION_INTERACT",

  // Secondary actions
  PLAYER_CHANGE_WEAPON = "PLAYER_CHANGE_WEAPON",
  PLAYER_BUILD_MENU = "PLAYER_BUILD_MENU",

  // Game flow controls
  GAME_PAUSE = "GAME_PAUSE",
  GAME_RESTART = "GAME_RESTART",

  // Debug controls
  DEBUG_MENU = "DEBUG_MENU",
  DEBUG_SPAWN_ZOMBIE = "DEBUG_SPAWN_ZOMBIE",
  DEBUG_KILL_ZOMBIE = "DEBUG_KILL_ZOMBIE",
}
